### PR TITLE
Maximize 2D head plot

### LINKED ISSUE #6: Increase head plot size
Hey @sappelhoff, I am starting to use your package to create nice visualizations for my studies. I hope you are aware that this means new issues and PRs will be incoming 😄!

First, I think the default head size when plotting coordinates with `plot_coords()` is rather small:

```python
fig, ax = plot_coords(coords)
```

before

I can increase/maximize it afterwards by:

```python
ax.set_axis_off()
fig.set_tight_layout(True)
ax.set_xlim([-1.1, 1.1])
ax.set_ylim([-1.1, 1.1])
```
after

Would you be OK with including this by default? If yes, where would you prefer to do it?

### PR DESCRIPTION
**Pull request by cbrnr**
Fixes #6.

### CODE REVIEW

**Comment by cbrnr** [comment]
Let's see how this looks. I also have a question about the hline and vline – they seem to be on top of the electrode markers, even though they are drawn before. Any ideas how to fix this? `zorder` maybe?

**Comment by cbrnr** [comment]
Fixed the order.

**Comment by cbrnr** [comment]
New default look:
new

**Review by sappelhoff — APPROVED** [review]
LGTM!

**Comment by sappelhoff** [comment]
- Can you please add a whatsnew entry? Please pull "main" before doing that!
- Can you please add yourself to CITATION.cff?

**Comment by sappelhoff** [comment]
sounds reasonable --- I welcome all these low hanging fruits for viz -- especially if you are testing this right now and missing this as a feature. As long as we don't go overboard, because the viz should remain a minor aspect of this package :-)

**Comment by cbrnr** [comment]
I agree. I'm trying to get the default viz to look clean and I think dotted lines are definitely useful. We don't have to introduce another parameter to show/hide them, this can be done afterwards by fiddling with the figure (which is of course much more complicated). Your call, LMK!

**Comment by cbrnr** [comment]
Larger electrodes and dotted center lines:

Figure_1

**Comment by sappelhoff** [comment]
I'd say go ahead :+1:

**Comment by cbrnr** [comment]
OK! Now another thing (hopefully the last for this PR): why are the text labels slightly off? Should we introduce some way to control this? E.g. I would like to be able to center them inside the circles. Another use case would be to move them so that they do not overlap the circles at all. Maybe in another PR?

**Comment by sappelhoff** [comment]
> E.g. I would like to be able to center them inside the circles. Another use case would be to move them so that they do not overlap the circles at all. Maybe in another PR?

feel free to add it here -- unless you don't have any more time, then we can postpone.

**Comment by sappelhoff** [comment]
if you pull `main`, we will get the docs preview :-)

it's quite annoying that I always have to approve your workflow right now, but that'll soon change when we merge this

**Comment by cbrnr** [comment]
Done. The circles and text position can already be changes with the `scatter_kwargs` and `text_kwargs`, so no need to add anything.

**Comment by sappelhoff** [comment]
Thanks @cbrnr!

**Pull request merged**
